### ISSUE TITLE
chore: Add Dev Deployment on Netlify and Link it as a Custom Property on the GitHub Repo

### ISSUE THREAD

**Issue by MFarabi619** [cuhacking/2025#58]
We currently don't have a proper dev deployment to share around. We're using preview links like [this](https://deploy-preview-54--cuhacking-portal-test-deployment.netlify.app/docs) one which can be out of date and cause mayhem in communication.

See [here](https://github.com/MFarabi619/stack-builder) for an example of something that would be really valuable.

| | |
|-|-|
| ![image](https://github.com/user-attachments/assets/4798c72a-8308-4431-adae-1d83e296db23) | ![image](https://github.com/user-attachments/assets/7d640f4c-005d-480c-b9f6-d4a05d19236f) |

As an aside, consider reaching out to Netlify/Vercel for a sponsorship for team plans. Would really really make our lives easier.

**Comment by HasithDeAlwis** [comment]
Would this server as a dev deployment?
https://cuhacking-portal-test-deployment.netlify.app
Its updated each time main is updated

**Comment by MFarabi619** [comment]
Yes that works, can we rename it to `cuhacking-portal-dev.netlify.app`?

You also want to make sure it's not indexed on google otherwise it'll steal SEO from your main deployment :laughing: There should be options in Netlify for it

**Comment by HasithDeAlwis** [comment]
@JowiAoun could you confirm whether or not this PR should be closed? From my understanding, we are migrating to AWS even for our preview deployments.

**Comment by JowiAoun** [comment]
Production environment should be on AWS. For the dev and previews, it may add more complications to have away from AWS.

Two different providers will bring overhead and complications, because Netlify & Vercel don't allow for containerized deployments, which we need to keep consistency.

I will give AWS a try for all environments, but the free tier instance may or may not be enough to support prod/dev/previews. Closing this until we need to discuss different deployment options again.

**Comment by JowiAoun** [comment]
Production environment should be on AWS. For the dev and previews, it may add more complications to have away from AWS.

Two different providers will bring overhead and complications, because Netlify & Vercel don't allow for containerized deployments, which we need to keep consistency.

I will give AWS a try for all environments, but the free tier instance may or may not be enough to support prod/dev/previews. Closing this until we need to discuss different deployment options again.
